---
- name: Run a Command
  hosts: nodes
  become: yes
  tasks:
    - name: Check UPTime
      shell: 'uptime'
      register: shell_output

    - name: Print the output
      debug:
        msg: "{{ shell_output.stdout_lines }}"



